### ISSUE TITLE
Review-SRS-Team17: Priorities of requirements could be defined better

### ISSUE THREAD

**Issue by JasperLeungGit** [NicLobo/Capstone-yoGERT#11]
All of the priorities for requirements are either 4 or 5, and there isn't anything in the document to define what these numbers mean. Giving a wider range of priorities to the requirements and adding some clarification for these numbers could be helpful for identifying priority requirements.

@samm82

**Comment by A454545** [comment]
The priority system was used from the Modified Volere Template description. The template was referenced at the beginning of the document to be able to use its formatting styles and systems.
