### ISSUE TITLE
Review-SRS-Team17: Same Planned Date For All Requirements

### ISSUE THREAD

**Issue by LilVegedog** [NicLobo/Capstone-yoGERT#12]
The SRS provides priorities and phase-in dates for all of the requirements and also potential conflicts between the requirements. However all of the requirements have the same phase-in date on November 14. It would be helpful if the team can plan the phase-in dates differently for each specific requirement according to its conflicts and priority, as some of the requirements need to be satisfied before other requirements can start being implemented.

@samm82

**Comment by A454545** [comment]
The team have worked on giving more appropriate dates as they gotten more familiar with the existing software.
