### ISSUE TITLE
Team17 Review: Tasks

### ISSUE THREAD

**Issue by vickysmt** [NicLobo/Capstone-yoGERT#13]
Tasks could be more in-depth with more details. This section could include the expected completion date of each task and the approaches that will be used to deliver the product, etc. A visual illustration such as a Gantt Chart may be helpful here as well.

@samm82

**Comment by A454545** [comment]
Our team structured their tasks based on the course's recommended deliverables. However the team is using both Team's task planner and Github issues to be organized the schedule for the deliverables. We just never saw Gantt Chart as something we will use day to day.
