### ISSUE TITLE
Team 16 Review: FMEA formatting is inconsistent and confusing

### ISSUE THREAD

**Issue by jsrebrnjak** [NicLobo/Capstone-yoGERT#19]
The FMEA table format is inconsistent and confusing for readers. Specifically, subpoints in sections such as "Causes of Failure", "Recommended Actions",  and "SR" should directly correlate to each other. For example, if a failure mode requires 3 causes of failure labelled a, b, and c, there should be subpoints a, b, and c in "Recommended Actions" and "SR" that correlate to each cause of failure. One confusing example in your table is for the failure mode "Processed GPS data is too large to be stored in the output directory".  This failure mode lists 3 causes of failure labelled a, b, and c and only one recommended action labelled b. Does this recommended action only correlate to failure b or does it apply to all 3 failure modes?

**Comment by rangaran** [comment]
All recommended actions correspond to their respective cause of failure. Fixed other numbering issues.
