### ISSUE TITLE
Team15 Review: NFR System Tests in VnV Plan

### ISSUE THREAD

**Issue by agentvv** [NicLobo/Capstone-yoGERT#24]
The "How test will be performed" section of some NFR system tests (test-id1, test-id3, test-id4, test-id5) read more as a test case derivation rather than a description of how the test will be performed. The later NFR system tests (test-id6, test-id7, test-id8, test-id9, test-id10) use this section correctly.

@samm82

**Comment by f1377v** [comment]
Design verification is lacking a detailed way to verify front end design decisions. Heuristics checklists can help with the assessment of the overall layout of the UI.

**Comment by rangaran** [comment]
It is mentioned under "how the test will be performed"
