### ISSUE TITLE
Team15 Review: Desing Verification in VnV Plan

### ISSUE THREAD

**Issue by f1377v** [NicLobo/Capstone-yoGERT#25]
Design verification is lacking a detailed way to verify front end design decisions. Heuristics performed by a group of 3 to 5 people (individually) and then collecting all the feedbacks in a session can help with the assessment of different aspects of the human computer interaction.
@samm82

**Comment by rangaran** [comment]
I feel like testing based on feedback can be done one person at a time or in a group. Both produce their own version of the results.
