### ISSUE TITLE
Review-VnVPlan-Team32: Unit Testing could be refined

### ISSUE THREAD

**Issue by bobotie23** [NicLobo/Capstone-yoGERT#32]
Again, great VnV guys. Just a few suggestions.

I think your group needs to add more stuff on Unit Test Section. I do find two excellent unit testing cases in your report, which are test-id7 and test-id8 in section 5.2.4. And my suggestion is to move these cases to the part about Unit Test Description. Perhaps you could solve this by adding a new subsection called '6.3 Tests for Nonfunctional Requirements'.

Furthermore, I highly encourage you guys to put on more graphs, which would provide the readers with easy and clear understanding

**Comment by NicLobo** [comment]
Added section Tests for Nonfunctional Requirements
