### ISSUE TITLE
Review Design Doc Team 14: Unclear Formalized Notation

### ISSUE THREAD

**Issue by namit-c** [NicLobo/Capstone-yoGERT#51]
I found that the notation used some of the modules to be a little confusing and unclear. I think it would've been more helpful to include an explanation in natural language in conjunction with the formalized notation. I think an example of this can be found in the module 'Network Graph' in the method description of 'get_nearest_node.' The variable 's' does not seem to be defined and it also is unclear whether a list of nodes is being returned or a single node. The index returned is also unclear if we look at just the notation (it can be understood a little better when you know the method name).

Namit Chopra
400196353
choprn9

**Comment by smita7** [comment]
Replaced unclear and confusion notation
