### ISSUE TITLE
Review Design Doc Team 14: Inconsistency in MIS

### ISSUE THREAD

**Issue by AndrewBal802** [NicLobo/Capstone-yoGERT#52]
In the MIS, in terms of the variable naming and function naming is a bit hard to read given the in consistent conventions used when multiple words are involved. For example, there is a mix between camel case, separated by underscores or all words lower cased.

Andrew Balmakund
400182420
balmakua

**Comment by smita7** [comment]
Closed by making all variable and funcition names camel cased
