### ISSUE TITLE
Review Design Doc Team 14: Unclear input

### ISSUE THREAD

**Issue by brandonduong** [NicLobo/Capstone-yoGERT#54]
For the MIS of Data Transformation Module, I found it unclear on what the inputs are for GenGraphInput, GenShortInput, and GenAltInput, specifically about the parts that refer to "with mode detected", what that exactly means, and how that is different from the input for GenALInput.

Brandon Duong
400210462
duongb9

**Comment by rangaran** [comment]
Closed since generic module instead.
