### ISSUE TITLE
Legends on the Mapping module

### ISSUE THREAD

**Issue by A454545** [NicLobo/Capstone-yoGERT#83]

**Comment by A454545** [comment]
Legend for route generation:
- icons for point marker
- colors for route types.

**Comment by NicLobo** [comment]
Legend should:

define colours for each route type ( red-stop yellow-walk green-drive)

define icons for each route type (I.e car icon for drive type)

**Comment by smita7** [comment]
Legend for activity locations:
- all activity locations should be same symbol(icon)
- different colours for different types of activity locations
